# Определяем версию синтаксиса GitLab CI
stages:
  - test  # Один этап — тестирование

# Задание для этапа test
test_nginx:
  stage: test
  script:
    # Проверяем, установлен ли nginx, и выводим его версию
    - which nginx && nginx -v
  tags:
    - shell  # Указываем, что задание должно выполняться на раннере с тегом 'shell'
